name: Build OpenShockClock for Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install MSYS2 and GTK dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-gobject
            mingw-w64-x86_64-adwaita-icon-theme

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
        shell: bash

      - name: Build Windows Executable
        run: |
          pyinstaller --onefile \
            --add-data "icons:icons" \
            --add-binary "$(python -c 'import gi; print(gi._gi.__file__)')":. \
            --add-binary "$(python -c 'import gi; print(gi.get_required_version("Gtk"))')":. \
            --name OpenShockClock \
            --windowed \
            openshockclock.py
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenShockClock-Windows
          path: dist/OpenShockClock.exe
          retention-days: 5
