name: Build OpenShockClock for Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Install MSYS2 and GTK dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-gtk4
            mingw-w64-x86_64-python-gobject
            mingw-w64-x86_64-python-requests
            mingw-w64-x86_64-python-dotenv
            mingw-w64-x86_64-adwaita-icon-theme

      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install pygobject requests python-dotenv

      - name: Build Windows Executable
        shell: bash
        run: |
          pyinstaller --onefile \
            --add-data "icons:icons" \
            --name OpenShockClock \
            --windowed \
            openshockclock.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenShockClock-Windows
          path: dist/OpenShockClock.exe
          retention-days: 5
